### ISSUE TITLE
SysEx support?

### ISSUE THREAD

**Issue by Harvie** [jmendeth/trinket-midi-adapter#2]
Does this have support for MIDI SysEx messages?

**Comment by mildsunrise** [comment]
[It does.](https://github.com/jmendeth/trinket-midi-adapter/blob/master/src/main.cpp#L86) But I've never had the opportunity to test it.

**Comment by mildsunrise** [comment]
If you find any bug, let me know. Also, beware this uses software for both UART *and* USB, so there may be message loss. This project is not intended for production use.
